### ISSUE TITLE
Migrate common UI components shown in website/account-manager to ui-js

### ISSUE THREAD

**Issue by denistsoi** [thenewboston-developers/ui-js#11]
- https://github.com/thenewboston-developers/Website/tree/development/src/components
- https://github.com/thenewboston-developers/Account-Manager/tree/master/src/renderer/components

I've narrowed the common components that exist in both as the following:

```
FormComponents
FormElements
Modal
Qr
Toast
```

The initial intention was to be able to extract the Website components for the community to reuse those components in their respective projects - but feel this may bloat this repo.

How do you envisage `ui-js` @angle943 ?

**Comment by angle943** [comment]
The FormComponents and FormElements will be updated pretty soon, so I am holding off on that. I want to hold off on the modal one right now too, as it might get updated pretty significantly. You can create issues for the `Qr` and `Toast` one, separately, and I can put bounties on it

**Comment by denistsoi** [comment]
No problems I'll create some PRs for those components

**Comment by angle943** [comment]
PAID
