### ISSUE TITLE
Migrate QR code component

### ISSUE THREAD

**Issue by denistsoi** [thenewboston-developers/ui-js#12]
As stated in https://github.com/thenewboston-developers/ui-js/issues/11

We want to migrate QR code from website into `ui-js`.

This aims to consolidate components in `thenewboston` applications (Website/Account-manager).

**Comment by angle943** [comment]
storybook & tests as requirements

**Comment by denistsoi** [comment]
This issue and respective PR https://github.com/thenewboston-developers/ui-js/pull/13 should be closed. Following up so we can close this and be remitted for the work. Thanks

**Comment by angle943** [comment]
PAID
