### ISSUE TITLE
Migrate Toast Component

### ISSUE THREAD

**Issue by denistsoi** [thenewboston-developers/ui-js#15]
As stated in #11

We want to migrate QR code from website into ui-js.

This aims to consolidate components in thenewboston applications (Website/Account-manager).

**Comment by angle943** [comment]
also try to make tests & storybook component for it. That will be part of the requirement

**Comment by denistsoi** [comment]
HI there - this issue and respective PR https://github.com/thenewboston-developers/ui-js/issues/12 has been open for the past 19 days. Following up to close and be remitted for the work done here.
